import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className="text-6xl bg-black text-white">Hello World</div>
    {/* <button
      className="bg-red-500 text-white px-3 py-1 rounded-md font-semibold"
      onClick={() => {
        getAccount();
      }}>
      Connect
    </button> */}
  </>
);

export default Home;
